name: Deploy

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: sa-app-client
          heroku_email: jrk.mb.xm@gmail.com
          buildpack: https://github.com/mars/create-react-app-buildpack.git
